package com.example.demo.dao;

import com.example.demo.pojo.UserAssociateRole;

public interface UserAssociateRoleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_associate_rol
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer urid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_associate_rol
     *
     * @mbggenerated
     */
    int insert(UserAssociateRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_associate_rol
     *
     * @mbggenerated
     */
    int insertSelective(UserAssociateRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_associate_rol
     *
     * @mbggenerated
     */
    UserAssociateRole selectByPrimaryKey(Integer urid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_associate_rol
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(UserAssociateRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_associate_rol
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(UserAssociateRole record);
}