package com.example.demo.pojo;

public class Menu {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column menu.MenuId
     *
     * @mbggenerated
     */
    private Integer menuid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column menu.MenuName
     *
     * @mbggenerated
     */
    private String menuname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column menu.MenuNumber
     *
     * @mbggenerated
     */
    private Integer menunumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column menu.MenuLevel
     *
     * @mbggenerated
     */
    private Integer menulevel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column menu.ParentNumber
     *
     * @mbggenerated
     */
    private Integer parentnumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column menu.MenuLink
     *
     * @mbggenerated
     */
    private String menulink;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column menu.PermissionId
     *
     * @mbggenerated
     */
    private Integer permissionid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column menu.MenuId
     *
     * @return the value of menu.MenuId
     *
     * @mbggenerated
     */
    public Integer getMenuid() {
        return menuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column menu.MenuId
     *
     * @param menuid the value for menu.MenuId
     *
     * @mbggenerated
     */
    public void setMenuid(Integer menuid) {
        this.menuid = menuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column menu.MenuName
     *
     * @return the value of menu.MenuName
     *
     * @mbggenerated
     */
    public String getMenuname() {
        return menuname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column menu.MenuName
     *
     * @param menuname the value for menu.MenuName
     *
     * @mbggenerated
     */
    public void setMenuname(String menuname) {
        this.menuname = menuname == null ? null : menuname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column menu.MenuNumber
     *
     * @return the value of menu.MenuNumber
     *
     * @mbggenerated
     */
    public Integer getMenunumber() {
        return menunumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column menu.MenuNumber
     *
     * @param menunumber the value for menu.MenuNumber
     *
     * @mbggenerated
     */
    public void setMenunumber(Integer menunumber) {
        this.menunumber = menunumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column menu.MenuLevel
     *
     * @return the value of menu.MenuLevel
     *
     * @mbggenerated
     */
    public Integer getMenulevel() {
        return menulevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column menu.MenuLevel
     *
     * @param menulevel the value for menu.MenuLevel
     *
     * @mbggenerated
     */
    public void setMenulevel(Integer menulevel) {
        this.menulevel = menulevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column menu.ParentNumber
     *
     * @return the value of menu.ParentNumber
     *
     * @mbggenerated
     */
    public Integer getParentnumber() {
        return parentnumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column menu.ParentNumber
     *
     * @param parentnumber the value for menu.ParentNumber
     *
     * @mbggenerated
     */
    public void setParentnumber(Integer parentnumber) {
        this.parentnumber = parentnumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column menu.MenuLink
     *
     * @return the value of menu.MenuLink
     *
     * @mbggenerated
     */
    public String getMenulink() {
        return menulink;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column menu.MenuLink
     *
     * @param menulink the value for menu.MenuLink
     *
     * @mbggenerated
     */
    public void setMenulink(String menulink) {
        this.menulink = menulink == null ? null : menulink.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column menu.PermissionId
     *
     * @return the value of menu.PermissionId
     *
     * @mbggenerated
     */
    public Integer getPermissionid() {
        return permissionid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column menu.PermissionId
     *
     * @param permissionid the value for menu.PermissionId
     *
     * @mbggenerated
     */
    public void setPermissionid(Integer permissionid) {
        this.permissionid = permissionid;
    }
}