package com.example.demo.pojo;

public class Permission {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column permission.PermissionId
     *
     * @mbggenerated
     */
    private Integer permissionid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column permission.RPid
     *
     * @mbggenerated
     */
    private Integer rpid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column permission.PermissionName
     *
     * @mbggenerated
     */
    private String permissionname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column permission.PermissionDesc
     *
     * @mbggenerated
     */
    private String permissiondesc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column permission.PermissionCode
     *
     * @mbggenerated
     */
    private Integer permissioncode;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column permission.PermissionId
     *
     * @return the value of permission.PermissionId
     *
     * @mbggenerated
     */
    public Integer getPermissionid() {
        return permissionid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column permission.PermissionId
     *
     * @param permissionid the value for permission.PermissionId
     *
     * @mbggenerated
     */
    public void setPermissionid(Integer permissionid) {
        this.permissionid = permissionid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column permission.RPid
     *
     * @return the value of permission.RPid
     *
     * @mbggenerated
     */
    public Integer getRpid() {
        return rpid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column permission.RPid
     *
     * @param rpid the value for permission.RPid
     *
     * @mbggenerated
     */
    public void setRpid(Integer rpid) {
        this.rpid = rpid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column permission.PermissionName
     *
     * @return the value of permission.PermissionName
     *
     * @mbggenerated
     */
    public String getPermissionname() {
        return permissionname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column permission.PermissionName
     *
     * @param permissionname the value for permission.PermissionName
     *
     * @mbggenerated
     */
    public void setPermissionname(String permissionname) {
        this.permissionname = permissionname == null ? null : permissionname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column permission.PermissionDesc
     *
     * @return the value of permission.PermissionDesc
     *
     * @mbggenerated
     */
    public String getPermissiondesc() {
        return permissiondesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column permission.PermissionDesc
     *
     * @param permissiondesc the value for permission.PermissionDesc
     *
     * @mbggenerated
     */
    public void setPermissiondesc(String permissiondesc) {
        this.permissiondesc = permissiondesc == null ? null : permissiondesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column permission.PermissionCode
     *
     * @return the value of permission.PermissionCode
     *
     * @mbggenerated
     */
    public Integer getPermissioncode() {
        return permissioncode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column permission.PermissionCode
     *
     * @param permissioncode the value for permission.PermissionCode
     *
     * @mbggenerated
     */
    public void setPermissioncode(Integer permissioncode) {
        this.permissioncode = permissioncode;
    }
}