package com.example.demo.pojo;

public class RolePermission {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role_permission.RPid
     *
     * @mbggenerated
     */
    private Integer rpid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role_permission.RoleId
     *
     * @mbggenerated
     */
    private Integer roleid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role_permission.PermissionId
     *
     * @mbggenerated
     */
    private Integer permissionid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role_permission.RPid
     *
     * @return the value of role_permission.RPid
     *
     * @mbggenerated
     */
    public Integer getRpid() {
        return rpid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role_permission.RPid
     *
     * @param rpid the value for role_permission.RPid
     *
     * @mbggenerated
     */
    public void setRpid(Integer rpid) {
        this.rpid = rpid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role_permission.RoleId
     *
     * @return the value of role_permission.RoleId
     *
     * @mbggenerated
     */
    public Integer getRoleid() {
        return roleid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role_permission.RoleId
     *
     * @param roleid the value for role_permission.RoleId
     *
     * @mbggenerated
     */
    public void setRoleid(Integer roleid) {
        this.roleid = roleid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role_permission.PermissionId
     *
     * @return the value of role_permission.PermissionId
     *
     * @mbggenerated
     */
    public Integer getPermissionid() {
        return permissionid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role_permission.PermissionId
     *
     * @param permissionid the value for role_permission.PermissionId
     *
     * @mbggenerated
     */
    public void setPermissionid(Integer permissionid) {
        this.permissionid = permissionid;
    }
}