package com.example.demo.pojo;

public class UserRole {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_role.RoleId
     *
     * @mbggenerated
     */
    private Integer roleid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_role.RoleName
     *
     * @mbggenerated
     */
    private String rolename;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_role.RoleDesc
     *
     * @mbggenerated
     */
    private String roledesc;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_role.RoleId
     *
     * @return the value of user_role.RoleId
     *
     * @mbggenerated
     */
    public Integer getRoleid() {
        return roleid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_role.RoleId
     *
     * @param roleid the value for user_role.RoleId
     *
     * @mbggenerated
     */
    public void setRoleid(Integer roleid) {
        this.roleid = roleid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_role.RoleName
     *
     * @return the value of user_role.RoleName
     *
     * @mbggenerated
     */
    public String getRolename() {
        return rolename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_role.RoleName
     *
     * @param rolename the value for user_role.RoleName
     *
     * @mbggenerated
     */
    public void setRolename(String rolename) {
        this.rolename = rolename == null ? null : rolename.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_role.RoleDesc
     *
     * @return the value of user_role.RoleDesc
     *
     * @mbggenerated
     */
    public String getRoledesc() {
        return roledesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_role.RoleDesc
     *
     * @param roledesc the value for user_role.RoleDesc
     *
     * @mbggenerated
     */
    public void setRoledesc(String roledesc) {
        this.roledesc = roledesc == null ? null : roledesc.trim();
    }
}