package com.example.demo.pojo;

public class UserAssociateRole {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_associate_rol.URid
     *
     * @mbggenerated
     */
    private Integer urid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_associate_rol.RoleId
     *
     * @mbggenerated
     */
    private Integer roleid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_associate_rol.UserId
     *
     * @mbggenerated
     */
    private Integer userid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_associate_rol.URid
     *
     * @return the value of user_associate_rol.URid
     *
     * @mbggenerated
     */
    public Integer getUrid() {
        return urid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_associate_rol.URid
     *
     * @param urid the value for user_associate_rol.URid
     *
     * @mbggenerated
     */
    public void setUrid(Integer urid) {
        this.urid = urid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_associate_rol.RoleId
     *
     * @return the value of user_associate_rol.RoleId
     *
     * @mbggenerated
     */
    public Integer getRoleid() {
        return roleid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_associate_rol.RoleId
     *
     * @param roleid the value for user_associate_rol.RoleId
     *
     * @mbggenerated
     */
    public void setRoleid(Integer roleid) {
        this.roleid = roleid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_associate_rol.UserId
     *
     * @return the value of user_associate_rol.UserId
     *
     * @mbggenerated
     */
    public Integer getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_associate_rol.UserId
     *
     * @param userid the value for user_associate_rol.UserId
     *
     * @mbggenerated
     */
    public void setUserid(Integer userid) {
        this.userid = userid;
    }
}