package com.example.demo.pojo;

public class User {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.UserId
     *
     * @mbggenerated
     */
    private Integer userid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.UserName
     *
     * @mbggenerated
     */
    private String username;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.UserPassword
     *
     * @mbggenerated
     */
    private String userpassword;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.UserType
     *
     * @mbggenerated
     */
    private String usertype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.UserCity
     *
     * @mbggenerated
     */
    private String usercity;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.UserJob
     *
     * @mbggenerated
     */
    private String userjob;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.UserId
     *
     * @return the value of user.UserId
     *
     * @mbggenerated
     */
    public Integer getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.UserId
     *
     * @param userid the value for user.UserId
     *
     * @mbggenerated
     */
    public void setUserid(Integer userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.UserName
     *
     * @return the value of user.UserName
     *
     * @mbggenerated
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.UserName
     *
     * @param username the value for user.UserName
     *
     * @mbggenerated
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.UserPassword
     *
     * @return the value of user.UserPassword
     *
     * @mbggenerated
     */
    public String getUserpassword() {
        return userpassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.UserPassword
     *
     * @param userpassword the value for user.UserPassword
     *
     * @mbggenerated
     */
    public void setUserpassword(String userpassword) {
        this.userpassword = userpassword == null ? null : userpassword.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.UserType
     *
     * @return the value of user.UserType
     *
     * @mbggenerated
     */
    public String getUsertype() {
        return usertype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.UserType
     *
     * @param usertype the value for user.UserType
     *
     * @mbggenerated
     */
    public void setUsertype(String usertype) {
        this.usertype = usertype == null ? null : usertype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.UserCity
     *
     * @return the value of user.UserCity
     *
     * @mbggenerated
     */
    public String getUsercity() {
        return usercity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.UserCity
     *
     * @param usercity the value for user.UserCity
     *
     * @mbggenerated
     */
    public void setUsercity(String usercity) {
        this.usercity = usercity == null ? null : usercity.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.UserJob
     *
     * @return the value of user.UserJob
     *
     * @mbggenerated
     */
    public String getUserjob() {
        return userjob;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.UserJob
     *
     * @param userjob the value for user.UserJob
     *
     * @mbggenerated
     */
    public void setUserjob(String userjob) {
        this.userjob = userjob == null ? null : userjob.trim();
    }
}